#!/bin/sh

MVN=$HOME/tools/maven/maven3/bin/mvn
AGENTPATH="`pwd`/beaker-maven3-agent/target/beaker-maven3-agent-0.1-SNAPSHOT.jar"

MAVEN_OPTS="$MAVEN_OPTS -javaagent:${AGENTPATH}"
#MAVEN_OPTS="$MAVEN_OPTS -Daj.weaving.verbose=true -Dorg.aspectj.weaver.showWeaveInfo=true"
MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.handler=com.sonatype.beaker.core.StreamMeepHandler"

export MAVEN_OPTS

exec $MVN "$@"