#!/bin/sh

MVN=$HOME/tools/maven/maven3/bin/mvn
AGENTPATH="`pwd`/beaker-maven3/target/beaker-maven3-0.1-SNAPSHOT.jar"

MAVEN_OPTS="$MAVEN_OPTS -javaagent:${AGENTPATH}"
#MAVEN_OPTS="$MAVEN_OPTS -Daj.weaving.verbose=true -Dorg.aspectj.weaver.showWeaveInfo=true"

MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.log.level=DEBUG"
MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.log.console.threshold=INFO"
MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.log.file=`pwd`/beaker.log"
MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.log.file.threshold=TRACE"

MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.handler=com.sonatype.beaker.core.handler.FileHandler"
MAVEN_OPTS="$MAVEN_OPTS -Dbeaker.handler.file=`pwd`/beaker.xmeep"

export MAVEN_OPTS

exec $MVN "$@"